foreground            #DBF1F3
background            #141018
cursor                #7A8A8C
selection_background  #DBF1F3
selection_foreground  #141018

# Standard colors
color0                #3C3840
color1                #55acbe 
color2                #27658d 
color3                #011d41
color4                #033858
color5                #27658d
color6                #55acbe
color7                #a6eaf2

# Bright colors
color8                #889FA1
color9                #55acbe 
color10               #27658d 
color11               #011d41
color12               #033858
color13               #27658d
color14               #55acbe
color15               #a6eaf2
