[colors-dark]
foreground=E7E7EF
background=121114
cursor=DBF1F3 E7E7EF
selection-foreground=121114
selection-background=E7E7EF

# Standard colors
regular0=3C3840
regular1=55ACBE
regular2=27658D
regular3=011D41
regular4=033858
regular5=27658D
regular6=55ACBE
regular7=A6EAF2

# Bright colors
bright0=889FA1
bright1=55ACBE
bright2=27658D
bright3=011D41
bright4=033858
bright5=27658D
bright6=55ACBE
bright7=A6EAF2
