foreground            #D5FEDE
background            #1E211E
cursor                #86B391
selection_background  #D5FEDE
selection_foreground  #1E211E

# Standard colors
color0                #444744
color1                #148891 
color2                #386943
color3                #148891
color4                #58A468
color5                #09D6CC
color6                #87FBA1
color7                #BAF5C8

# Bright colors
color8                #83AB8C
color9                #148891
color10               #386943
color11               #148891
color12               #58A468
color13               #09D6CC
color14               #87FBA1
color15               #BAF5C8
