foreground            #DDC6E2
background            #201927
cursor                #9E72B2
selection_background  #DDC6E2
selection_foreground  #201927

# Standard colors
color0                #473F4F
color1                #8240C7
color2                #5F1E82
color3                #B026FF 
color4                #933087
color5                #8240C7
color6                #9D5CAB
color7                #C6A5CD

# Bright colors
color8                #8A748F
color9                #8240C7
color10               #5F1E82
color11               #B026FF
color12               #933087
color13               #8240C7
color14               #9D5CAB
color15               #C6A5CD
