foreground            #E7F6FA
background            #0F1017
cursor                #76ABC7
selection_background  #E7F6FA
selection_foreground  #0F1017

# Standard colors
color0                #37383F
color1                #023866
color2                #056094
color3                #1487BB
color4                #8198B4
color5                #32B0D5
color6                #BAE6F1
color7                #D4EAF0

# Bright colors
color8                #94A4A8
color9                #023866
color10               #056094
color11               #1487BB
color12               #8198B4
color13               #32B0D5
color14               #BAE6F1
color15               #D4EAF0
