-- Dynamic border color used for theming
-- Generated by create_theme.sh - Theme Creation System

hl.config({
    general = {
        col = {
            active_border = { colors = { "rgba(D97E52ee)", "rgba(D9AD98ee)" }, angle = 45 },
        },
    },
})
