foreground            #FFEDFF
background            #201C27
cursor                #BA98D4
selection_background  #FFEDFF
selection_foreground  #201C27

# Standard colors
color0                #47424E
color1                #6C455F
color2                #7542AA
color3                #987C85
color4                #DA66EB
color5                #B3BDCC
color6                #FFCCFF
color7                #F6DDF6

# Bright colors
color8                #AD9BAD
color9                #6C455F
color10               #7542AA
color11               #987C85
color12               #DA66EB
color13               #B3BDCC
color14               #FFCCFF
color15               #F6DDF6
