[colors-dark]
foreground=EEFAF9
background=121212
cursor=D9607C EEFAF9 
selection-foreground=121212
selection-background=EEFAF9

# Standard colors
regular0=c18b8f
regular1=636083
regular2=7e7b9d
regular3=B85F66
regular4=4C8DC2
regular5=B1A2C7
regular6=FDB2A8
regular7=F6D0CB

# Bright colors
bright0=c18b8f
bright1=636083
bright2=7e7b9d
bright3=B85F66
bright4=4C8DC2
bright5=B1A2C7
bright6=FDB2A8
bright7=F6D0CB
