-- Dynamic border color used for theming
-- Generated by create_theme.sh - Theme Creation System

hl.config({
    general = {
        col = {
            active_border = { colors = { "rgba(D9607Cee)", "rgba(D9A1AEee)" }, angle = 45 },
        },
    },
})
