[colors-dark]
foreground=EEFAF9
background=121212
cursor=D97E52 EEFAF9 
selection-foreground=121212
selection-background=EEFAF9

# Standard colors
regular0=525f7a
regular1=2A4B5D
regular2=39667f
regular3=594845
regular4=606E73
regular5=8A756B
regular6=BF8365
regular7=D7B9AA

# Bright colors
bright0=525f7a
bright1=2A4B5D
bright2=39667f
bright3=594845
bright4=606E73
bright5=8A756B
bright6=BF8365
bright7=D7B9AA

