foreground            #F0EEE3
background            #101012
cursor                #C6C2B0
selection_background  #F0EEE3
selection_foreground  #101012

# Standard colors
color0                #39393A
color1                #8F7F71
color2                #9C957E
color3                #75A097
color4                #9EB39F
color5                #C4B092
color6                #D4CFAE
color7                #E1DFCE

# Bright colors
color8                #9E9C90
color9                #8F7F71
color10               #9C957E
color11               #75A097
color12               #9EB39F
color13               #C4B092
color14               #D4CFAE
color15               #E1DFCE
