[colors-dark]
foreground=E7E7EF
background=121114
cursor=8C8B99 E7E7EF
selection-foreground=121114
selection-background=E7E7EF

# Standard colors
regular0=3A393C
regular1=575478
regular2=433f73
regular3=4E556E
regular4=6C7A97
regular5=929EBB
regular6=BBBBD0
regular7=D4D5DF

# Bright colors
bright0=95959C
bright1=575478
bright2=433f73
bright3=4E556E
bright4=6C7A97
bright5=929EBB
bright6=BBBBD0
bright7=D4D5DF
