-- Dynamic border color used for theming
-- Generated by create_theme.sh - Theme Creation System

hl.config({
	general = {
		col = {
			active_border = { colors = { "rgba(E7E7EFee)", "rgba(D4D5DFee)" }, angle = 45 },
		},
	},
})
