[colors-dark]
foreground=F1F6E9
background=131315
cursor=131315 ACACBC
selection-foreground=131315
selection-background=F1F6E9

# Standard colors
regular0=3A3A3C
regular1=626255
regular2=67618F
regular3=B06E6B
regular4=ACAFCC
regular5=FFBC93
regular6=D7E6C0
regular7=E3EAD7

# Bright colors
bright0=9FA496
bright1=626255
bright2=67618F
bright3=B06E6B
bright4=ACAFCC
bright5=FFBC93
bright6=D7E6C0
bright7=E3EAD7
