foreground            #F1F6E9
background            #131315
cursor                #ACACBC
selection_background  #F1F6E9
selection_foreground  #131315

# Standard colors
color0                #3A3A3C
color1                #626255
color2                #67618F
color3                #B06E6B
color4                #ACAFCC
color5                #FFBC93
color6                #D7E6C0
color7                #E3EAD7

# Bright colors
color8                #9FA496
color9                #626255
color10               #67618F
color11               #B06E6B
color12               #ACAFCC
color13               #FFBC93
color14               #D7E6C0
color15               #E3EAD7
