[colors-dark]
foreground=EEFAF9
background=121212
cursor=66A4D9 EEFAF9 
selection-foreground=121212
selection-background=EEFAF9

# Standard colors
regular0=4A5D78
regular1=586275
regular2=4A5D78
regular3=727D89
regular4=A3A7B2
regular5=8FCADC
regular6=D6E2EB
regular7=E2E8ED

# Bright colors
bright0=4A5D78
bright1=586275
bright2=4A5D78
bright3=727D89
bright4=A3A7B2
bright5=8FCADC
bright6=D6E2EB
bright7=E2E8ED

