-- Dynamic border color used for theming
-- Generated by create_theme.sh - Theme Creation System

hl.config({
	general = {
		col = {
			active_border = { colors = { "rgba(8FCADCee)", "rgba(A7C2D9ee)" }, angle = 45 },
		},
	},
})
