[colors-dark]
foreground=EAEDF1
background=1D1E20
cursor=1D1E20 B1AA9D
selection-foreground=1D1E20
selection-background=EAEDF1

# Standard colors
regular0=434447
regular1=831E19
regular2=796649
regular3=5A7187
regular4=E24238
regular5=E0A162
regular6=C2CCD6
regular7=D8DDE2

# Bright colors
bright0=979B9E
bright1=831E19
bright2=796649
bright3=5A7187
bright4=E24238
bright5=E0A162
bright6=C2CCD6
bright7=D8DDE2
