#!/usr/bin/env bash

CRITICAL=70
temp=""

vendor=$(awk -F': ' '/vendor_id/ {print $2; exit}' /proc/cpuinfo)

if [ "$vendor" = "AuthenticAMD" ]; then
  for hw in /sys/class/hwmon/hwmon*; do
    [ "$(cat "$hw/name" 2>/dev/null)" = "k10temp" ] || continue

    # Prefer Tccd*
    for lbl in "$hw"/temp*_label; do
      label=$(cat "$lbl" 2>/dev/null)
      case "$label" in
        Tccd*)
          input="${lbl%_label}_input"
          val=$(cat "$input" 2>/dev/null)
          [ -n "$val" ] && temp=$((val / 1000)) && break 2
        ;;
      esac
    done

    # Fallback Tdie
    for lbl in "$hw"/temp*_label; do
      label=$(cat "$lbl" 2>/dev/null)
      [ "$label" = "Tdie" ] || continue
      input="${lbl%_label}_input"
      val=$(cat "$input" 2>/dev/null)
      [ -n "$val" ] && temp=$((val / 1000)) && break 2
    done
  done

elif [ "$vendor" = "GenuineIntel" ]; then
  for hw in /sys/class/hwmon/hwmon*; do
    [ "$(cat "$hw/name" 2>/dev/null)" = "coretemp" ] || continue

    for lbl in "$hw"/temp*_label; do
      label=$(cat "$lbl" 2>/dev/null)
      case "$label" in
        *Package*)
          input="${lbl%_label}_input"
          val=$(cat "$input" 2>/dev/null)
          [ -n "$val" ] && temp=$((val / 1000)) && break 2
        ;;
      esac
    done
  done
fi

# Fallback ACPI
if [ -z "$temp" ]; then
  for tz in /sys/class/thermal/thermal_zone*/temp; do
    val=$(cat "$tz" 2>/dev/null)
    [ -n "$val" ] && temp=$((val / 1000)) && break
  done
fi

# Formatting output
[ -z "$temp" ] && exit 1

if [ "$temp" -ge "$CRITICAL" ]; then
    icon="󱃂"
    class="critical"
    tooltip="Critical: $temp °C"
elif [ "$temp" -lt 40 ]; then
    icon="󱃃"
    class="cool"
    tooltip="Cool: $temp °C"
else
    icon="󰔏"
    class="normal"
    tooltip="Normal: $temp °C"
fi

printf '{"text":"%s","class":"%s","tooltip":"%s"}\n' \
    "$icon" "$class" "$tooltip"
