#!/usr/bin/env bash

DIRECTION="$1"
TYPE="$2"

case "$TYPE" in
    output)
        DEVICE="@DEFAULT_AUDIO_SINK@"
        ;;
    input)
        DEVICE="@DEFAULT_AUDIO_SOURCE@"
        ;;
    *)
        echo "Uso: $0 {up|down|toggle-mute} {output|input}"
        exit 1
        ;;
esac

case "$DIRECTION" in
    up)
        VOL=$(wpctl get-volume "$DEVICE" | awk '{print $2}')
        if awk "BEGIN {exit !($VOL < 1.0)}"; then
            wpctl set-volume "$DEVICE" 5%+
        fi
        ;;
    down)
        wpctl set-volume "$DEVICE" 5%-
        ;;
    toggle-mute)
        wpctl set-mute "$DEVICE" toggle
        ;;
    *)
        echo "Uso: $0 {up|down|toggle-mute} {output|input}"
        exit 1
        ;;
esac
