foreground            #EDF2F2
background            #212525
cursor                #879EA5
selection_background  #EDF2F2
selection_foreground  #212525

# Standard colors
color0                #474B4B
color1                #466C75
color2                #204A58
color3                #466C75
color4                #648A92
color5                #8FACB3
color6                #CCD9DB
color7                #DDE4E5

# Bright colors
color8                #9B9FA0
color9                #466C75 
color10               #204A58
color11               #466C75
color12               #648A92
color13               #8FACB3
color14               #CCD9DB
color15               #DDE4E5
