[colors-dark]
foreground=EDF2F2
background=212525
cursor=212525 879EA5
selection-foreground=212525
selection-background=EDF2F2

# Standard colors
regular0=474B4B
regular1=466C75
regular2=204A58
regular3=466C75
regular4=648A92
regular5=8FACB3
regular6=CCD9DB
regular7=DDE4E5

# Bright colors
bright0=9B9FA0
bright1=466C75
bright2=204A58
bright3=466C75
bright4=648A92
bright5=8FACB3
bright6=CCD9DB
bright7=DDE4E5
