[colors]
foreground=DDCFCC
background=2D2E30
cursor=2D2E30 957E7D
selection-foreground=2D2E30
selection-background=DDCFCC

# Standard colors
regular0=525355
regular1=957E7D
regular2=4D2D2E
regular3=8D473C
regular4=665C64
regular5=DD3D23
regular6=9F766D
regular7=C6B2AE

# Bright colors
bright0=8B7D79
bright1=957E7D
bright2=4D2D2E
bright3=8D473C
bright4=665C64
bright5=DD3D23
bright6=9F766D
bright7=C6B2AE
