foreground            #DDCFCC
background            #2D2E30
cursor                #957E7D
selection_background  #DDCFCC
selection_foreground  #2D2E30

# Standard colors
color0                #525355
color1                #957E7D
color2                #4D2D2E
color3                #8D473C
color4                #665C64
color5                #DD3D23
color6                #9F766D
color7                #C6B2AE

# Bright colors
color8                #8B7D79
color9                #957E7D
color10               #4D2D2E
color11               #8D473C
color12               #665C64
color13               #DD3D23
color14               #9F766D
color15               #C6B2AE
