foreground            #EEFAF9
background            #242223
cursor                #94ABBD
selection_background  #EEFAF9
selection_foreground  #242223

# Standard colors
color0                #4A4849
color1                #8A667E
color2                #3B5C81
color3                #8A667E
color4                #6B9FBF
color5                #D1B6BA
color6                #CDF0EF
color7                #DEEFEF

# Bright colors
color8                #9BA7A7
color9                #8A667E
color10               #3B5C81
color11               #8A667E
color12               #6B9FBF
color13               #D1B6BA
color14               #CDF0EF
color15               #DEEFEF
