[colors]
foreground=EEFAF9
background=242223
cursor=242223 94ABBD
selection-foreground=242223
selection-background=EEFAF9

# Standard colors
regular0=4A4849
regular1=8A667E
regular2=3B5C81
regular3=8A667E
regular4=6B9FBF
regular5=D1B6BA
regular6=CDF0EF
regular7=DEEFEF

# Bright colors
bright0=9BA7A7
bright1=8A667E
bright2=3B5C81
bright3=8A667E
bright4=6B9FBF
bright5=D1B6BA
bright6=CDF0EF
bright7=DEEFEF
