-- Dynamic border color used for theming
-- Generated by create_theme.sh - Theme Creation System

hl.config({
	general = {
		col = {
			active_border = { colors = { "rgba(6B9FBFee)", "rgba(273D66ee)" }, angle = 45 },
		},
	},
})
