foreground            #E7E7EF
background            #121114
cursor                #8C8B99
selection_background  #E7E7EF
selection_foreground  #121114

# Standard colors
color0                #3A393C
color1                #536477 
color2                #61748A 
color3                #4E556E
color4                #6C7A97
color5                #929EBB
color6                #BBBBD0
color7                #D4D5DF

# Bright colors
color8                #95959C
color9                #536477 
color10               #61748A 
color11               #4E556E
color12               #6C7A97
color13               #929EBB
color14               #BBBBD0
color15               #D4D5DF

