[colors-dark]
foreground=E7E7EF
background=121114
cursor=B3BDCC E7E7EF
selection-foreground=121114
selection-background=E7E7EF

# Standard colors
regular0=47424E
regular1=6C455F
regular2=7542AA
regular3=987C85
regular4=DA66EB
regular5=B3BDCC
regular6=FFCCFF
regular7=F6DDF6

# Bright colors
bright0=AD9BAD
bright1=6C455F
bright2=7542AA
bright3=987C85
bright4=DA66EB
bright5=B3BDCC
bright6=FFCCFF
bright7=F6DDF6
