[colors-dark]
foreground=E7E7EF
background=121114
cursor=E1DFCE E7E7EF
selection-foreground=121114
selection-background=E7E7EF

# Standard colors
regular0=39393A
regular1=8F7F71
regular2=9C957E
regular3=75A097
regular4=9EB39F
regular5=C4B092
regular6=D4CFAE
regular7=E1DFCE

# Bright colors
bright0=9E9C90
bright1=8F7F71
bright2=9C957E
bright3=75A097
bright4=9EB39F
bright5=C4B092
bright6=D4CFAE
bright7=E1DFCE
