[colors-dark]
foreground=EEFAF9
background=121212
cursor=6AA6D9 EEFAF9 
selection-foreground=121212
selection-background=EEFAF9

# Standard colors
regular0=1C415C
regular1=3E617E
regular2=6081A0
regular3=82A1C2
regular4=A4C1E4
regular5=C6E1FF
regular6=E8FFFF
regular7=FFFFFF

# Bright colors
bright0=1C415C
bright1=3E617E
bright2=6081A0
bright3=82A1C2
bright4=A4C1E4
bright5=C6E1FF
bright6=E8FFFF
bright7=FFFFFF

