-- Dynamic border color used for theming
-- Generated by create_theme.sh - Theme Creation System

hl.config({
    general = {
        col = {
            active_border = { colors = { "rgba(6AA6D9ee)", "rgba(ABC4D9ee)" }, angle = 45 },
        },
    },
})
