[colors-dark]
foreground=E7E7EF
background=121114
cursor=E7E7EF E7E7EF
selection-foreground=121114
selection-background=E7E7EF

# Standard colors
regular0=000102
regular1=57554F
regular2=66645E
regular3=71716B
regular4=88857B
regular5=A19B8D
regular6=BCB6A6
regular7=D5D2CA

# Bright colors
bright0=95938D
bright1=57554F
bright2=66645E
bright3=71716B
bright4=88857B
bright5=A19B8D
bright6=BCB6A6
bright7=D5D2CA
