foreground            #E8E5E0
background            #000102
cursor                #A1A39F
selection_background  #E8E5E0
selection_foreground  #000102

# Standard colors
color0                #000102
color1                #3D484E
color2                #5A605F
color3                #71716B
color4                #88857B
color5                #A19B8D
color6                #BCB6A6
color7                #D5D2CA

# Bright colors
color8                #95938D
color9                #3D484E
color10               #5A605F
color11               #71716B
color12               #88857B
color13               #A19B8D
color14               #BCB6A6
color15               #D5D2CA
